### ISSUE TITLE
cannot reat property 'match' of undefined

### ISSUE THREAD

**Issue by alexanderghose** [th3dougler/zoom-tracker#1]
hmm strange error i'm getting:
![image](https://user-images.githubusercontent.com/24878576/111629835-19250e80-87c8-11eb-8fd7-28ee8fb976a1.png)

it seems that the email and subject match, but mail.text is undefined for some reason. have you experienced this?
![image](https://user-images.githubusercontent.com/24878576/111629973-3a85fa80-87c8-11eb-95fa-73900bf7530a.png)

very much not a priority.. i'll just add some logging and see if it's something i missed in the config perhaps

**Comment by th3dougler** [comment]
Thank you for your feedback, it is a priority now!

I was unable to reproduce this error on my development environment, but noticed similar issues in the mail-listener2 package.

I rewrote the new mail checking function using inbox and mail-parser (which is what mail-listener is based upon), please pull the updated codebase and let me know if the same error crops up
